import lner
entities = {
    'countries': [
        {"values": ['Afghanistan'], "key": 'AF'},
        {"values": ['Åland Islands'], "key": 'AX'},
        {"values": ['Albania'], "key": 'AL'},
        {"values": ['Algeria'], "key": 'DZ'},
        {"values": ['American Samoa'], "key": 'AS'},
        {"values": ['AndorrA'], "key": 'AD'},
        {"values": ['Angola'], "key": 'AO'},
        {"values": ['Anguilla'], "key": 'AI'},
        {"values": ['Antarctica'], "key": 'AQ'},
        {"values": ['Antigua and Barbuda'], "key": 'AG'},
        {"values": ['Argentina'], "key": 'AR'},
        {"values": ['Armenia'], "key": 'AM'},
        {"values": ['Aruba'], "key": 'AW'},
        {"values": ['Australia'], "key": 'AU'},
        {"values": ['Austria'], "key": 'AT'},
        {"values": ['Azerbaijan'], "key": 'AZ'},
        {"values": ['Bahamas'], "key": 'BS'},
        {"values": ['Bahrain'], "key": 'BH'},
        {"values": ['Bangladesh'], "key": 'BD'},
        {"values": ['Barbados'], "key": 'BB'},
        {"values": ['Belarus'], "key": 'BY'},
        {"values": ['Belgium'], "key": 'BE'},
        {"values": ['Belize'], "key": 'BZ'},
        {"values": ['Benin'], "key": 'BJ'},
        {"values": ['Bermuda'], "key": 'BM'},
        {"values": ['Bhutan'], "key": 'BT'},
        {"values": ['Bolivia'], "key": 'BO'},
        {"values": ['Bosnia and Herzegovina'], "key": 'BA'},
        {"values": ['Botswana'], "key": 'BW'},
        {"values": ['Bouvet Island'], "key": 'BV'},
        {"values": ['Brazil'], "key": 'BR'},
        {"values": ['British Indian Ocean Territory'], "key": 'IO'},
        {"values": ['Brunei Darussalam'], "key": 'BN'},
        {"values": ['Bulgaria'], "key": 'BG'},
        {"values": ['Burkina Faso'], "key": 'BF'},
        {"values": ['Burundi'], "key": 'BI'},
        {"values": ['Cambodia'], "key": 'KH'},
        {"values": ['Cameroon'], "key": 'CM'},
        {"values": ['Canada'], "key": 'CA'},
        {"values": ['Cape Verde'], "key": 'CV'},
        {"values": ['Cayman Islands'], "key": 'KY'},
        {"values": ['Central African Republic'], "key": 'CF'},
        {"values": ['Chad'], "key": 'TD'},
        {"values": ['Chile'], "key": 'CL'},
        {"values": ['China'], "key": 'CN'},
        {"values": ['Christmas Island'], "key": 'CX'},
        {"values": ['Cocos (Keeling) Islands'], "key": 'CC'},
        {"values": ['Colombia'], "key": 'CO'},
        {"values": ['Comoros'], "key": 'KM'},
        {"values": ['Congo'], "key": 'CG'},
        {"values": ['Congo, The Democratic Republic of the'], "key": 'CD'},
        {"values": ['Cook Islands'], "key": 'CK'},
        {"values": ['Costa Rica'], "key": 'CR'},
        {"values": ['Cote D\'Ivoire'], "key": 'CI'},
        {"values": ['Croatia'], "key": 'HR'},
        {"values": ['Cuba'], "key": 'CU'},
        {"values": ['Cyprus'], "key": 'CY'},
        {"values": ['Czech Republic'], "key": 'CZ'},
        {"values": ['Denmark'], "key": 'DK'},
        {"values": ['Djibouti'], "key": 'DJ'},
        {"values": ['Dominica'], "key": 'DM'},
        {"values": ['Dominican Republic'], "key": 'DO'},
        {"values": ['Ecuador'], "key": 'EC'},
        {"values": ['Egypt'], "key": 'EG'},
        {"values": ['El Salvador'], "key": 'SV'},
        {"values": ['Equatorial Guinea'], "key": 'GQ'},
        {"values": ['Eritrea'], "key": 'ER'},
        {"values": ['Estonia'], "key": 'EE'},
        {"values": ['Ethiopia'], "key": 'ET'},
        {"values": ['Falkland Islands (Malvinas)'], "key": 'FK'},
        {"values": ['Faroe Islands'], "key": 'FO'},
        {"values": ['Fiji'], "key": 'FJ'},
        {"values": ['Finland'], "key": 'FI'},
        {"values": ['France'], "key": 'FR'},
        {"values": ['French Guiana'], "key": 'GF'},
        {"values": ['French Polynesia'], "key": 'PF'},
        {"values": ['French Southern Territories'], "key": 'TF'},
        {"values": ['Gabon'], "key": 'GA'},
        {"values": ['Gambia'], "key": 'GM'},
        {"values": ['Georgia'], "key": 'GE'},
        {"values": ['Germany'], "key": 'DE'},
        {"values": ['Ghana'], "key": 'GH'},
        {"values": ['Gibraltar'], "key": 'GI'},
        {"values": ['Greece'], "key": 'GR'},
        {"values": ['Greenland'], "key": 'GL'},
        {"values": ['Grenada'], "key": 'GD'},
        {"values": ['Guadeloupe'], "key": 'GP'},
        {"values": ['Guam'], "key": 'GU'},
        {"values": ['Guatemala'], "key": 'GT'},
        {"values": ['Guernsey'], "key": 'GG'},
        {"values": ['Guinea'], "key": 'GN'},
        {"values": ['Guinea-Bissau'], "key": 'GW'},
        {"values": ['Guyana'], "key": 'GY'},
        {"values": ['Haiti'], "key": 'HT'},
        {"values": ['Heard Island and Mcdonald Islands'], "key": 'HM'},
        {"values": ['Holy See (Vatican City State)'], "key": 'VA'},
        {"values": ['Honduras'], "key": 'HN'},
        {"values": ['Hong Kong'], "key": 'HK'},
        {"values": ['Hungary'], "key": 'HU'},
        {"values": ['Iceland'], "key": 'IS'},
        {"values": ['India'], "key": 'IN'},
        {"values": ['Indonesia'], "key": 'ID'},
        {"values": ['Iran, Islamic Republic Of'], "key": 'IR'},
        {"values": ['Iraq'], "key": 'IQ'},
        {"values": ['Ireland'], "key": 'IE'},
        {"values": ['Isle of Man'], "key": 'IM'},
        {"values": ['Israel'], "key": 'IL'},
        {"values": ['Italy'], "key": 'IT'},
        {"values": ['Jamaica'], "key": 'JM'},
        {"values": ['Japan'], "key": 'JP'},
        {"values": ['Jersey'], "key": 'JE'},
        {"values": ['Jordan'], "key": 'JO'},
        {"values": ['Kazakhstan'], "key": 'KZ'},
        {"values": ['Kenya'], "key": 'KE'},
        {"values": ['Kiribati'], "key": 'KI'},
        {"values": ['Korea, Democratic People\'S Republic of'], "key": 'KP'},
        {"values": ['Korea, Republic of'], "key": 'KR'},
        {"values": ['Kuwait'], "key": 'KW'},
        {"values": ['Kyrgyzstan'], "key": 'KG'},
        {"values": ['Lao People\'S Democratic Republic'], "key": 'LA'},
        {"values": ['Latvia'], "key": 'LV'},
        {"values": ['Lebanon'], "key": 'LB'},
        {"values": ['Lesotho'], "key": 'LS'},
        {"values": ['Liberia'], "key": 'LR'},
        {"values": ['Libyan Arab Jamahiriya'], "key": 'LY'},
        {"values": ['Liechtenstein'], "key": 'LI'},
        {"values": ['Lithuania'], "key": 'LT'},
        {"values": ['Luxembourg'], "key": 'LU'},
        {"values": ['Macao'], "key": 'MO'},
        {"values": ['Macedonia, The Former Yugoslav Republic of'], "key": 'MK'},
        {"values": ['Madagascar'], "key": 'MG'},
        {"values": ['Malawi'], "key": 'MW'},
        {"values": ['Malaysia'], "key": 'MY'},
        {"values": ['Maldives'], "key": 'MV'},
        {"values": ['Mali'], "key": 'ML'},
        {"values": ['Malta'], "key": 'MT'},
        {"values": ['Marshall Islands'], "key": 'MH'},
        {"values": ['Martinique'], "key": 'MQ'},
        {"values": ['Mauritania'], "key": 'MR'},
        {"values": ['Mauritius'], "key": 'MU'},
        {"values": ['Mayotte'], "key": 'YT'},
        {"values": ['Mexico'], "key": 'MX'},
        {"values": ['Micronesia, Federated States of'], "key": 'FM'},
        {"values": ['Moldova, Republic of'], "key": 'MD'},
        {"values": ['Monaco'], "key": 'MC'},
        {"values": ['Mongolia'], "key": 'MN'},
        {"values": ['Montserrat'], "key": 'MS'},
        {"values": ['Morocco'], "key": 'MA'},
        {"values": ['Mozambique'], "key": 'MZ'},
        {"values": ['Myanmar'], "key": 'MM'},
        {"values": ['Namibia'], "key": 'NA'},
        {"values": ['Nauru'], "key": 'NR'},
        {"values": ['Nepal'], "key": 'NP'},
        {"values": ['Netherlands'], "key": 'NL'},
        {"values": ['Netherlands Antilles'], "key": 'AN'},
        {"values": ['New Caledonia'], "key": 'NC'},
        {"values": ['New Zealand'], "key": 'NZ'},
        {"values": ['Nicaragua'], "key": 'NI'},
        {"values": ['Niger'], "key": 'NE'},
        {"values": ['Nigeria'], "key": 'NG'},
        {"values": ['Niue'], "key": 'NU'},
        {"values": ['Norfolk Island'], "key": 'NF'},
        {"values": ['Northern Mariana Islands'], "key": 'MP'},
        {"values": ['Norway'], "key": 'NO'},
        {"values": ['Oman'], "key": 'OM'},
        {"values": ['Pakistan'], "key": 'PK'},
        {"values": ['Palau'], "key": 'PW'},
        {"values": ['Palestinian Territory, Occupied'], "key": 'PS'},
        {"values": ['Panama'], "key": 'PA'},
        {"values": ['Papua New Guinea'], "key": 'PG'},
        {"values": ['Paraguay'], "key": 'PY'},
        {"values": ['Peru'], "key": 'PE'},
        {"values": ['Philippines'], "key": 'PH'},
        {"values": ['Pitcairn'], "key": 'PN'},
        {"values": ['Poland'], "key": 'PL'},
        {"values": ['Portugal'], "key": 'PT'},
        {"values": ['Puerto Rico'], "key": 'PR'},
        {"values": ['Qatar'], "key": 'QA'},
        {"values": ['Reunion'], "key": 'RE'},
        {"values": ['Romania'], "key": 'RO'},
        {"values": ['Russian Federation'], "key": 'RU'},
        {"values": ['RWANDA'], "key": 'RW'},
        {"values": ['Saint Helena'], "key": 'SH'},
        {"values": ['Saint Kitts and Nevis'], "key": 'KN'},
        {"values": ['Saint Lucia'], "key": 'LC'},
        {"values": ['Saint Pierre and Miquelon'], "key": 'PM'},
        {"values": ['Saint Vincent and the Grenadines'], "key": 'VC'},
        {"values": ['Samoa'], "key": 'WS'},
        {"values": ['San Marino'], "key": 'SM'},
        {"values": ['Sao Tome and Principe'], "key": 'ST'},
        {"values": ['Saudi Arabia'], "key": 'SA'},
        {"values": ['Senegal'], "key": 'SN'},
        {"values": ['Serbia and Montenegro'], "key": 'CS'},
        {"values": ['Seychelles'], "key": 'SC'},
        {"values": ['Sierra Leone'], "key": 'SL'},
        {"values": ['Singapore'], "key": 'SG'},
        {"values": ['Slovakia'], "key": 'SK'},
        {"values": ['Slovenia'], "key": 'SI'},
        {"values": ['Solomon Islands'], "key": 'SB'},
        {"values": ['Somalia'], "key": 'SO'},
        {"values": ['South Africa'], "key": 'ZA'},
        {"values": ['South Georgia and the South Sandwich Islands'], "key": 'GS'},
        {"values": ['Spain'], "key": 'ES'},
        {"values": ['Sri Lanka'], "key": 'LK'},
        {"values": ['Sudan'], "key": 'SD'},
        {"values": ['Suriname'], "key": 'SR'},
        {"values": ['Svalbard and Jan Mayen'], "key": 'SJ'},
        {"values": ['Swaziland'], "key": 'SZ'},
        {"values": ['Sweden'], "key": 'SE'},
        {"values": ['Switzerland'], "key": 'CH'},
        {"values": ['Syrian Arab Republic'], "key": 'SY'},
        {"values": ['Taiwan, Province of China'], "key": 'TW'},
        {"values": ['Tajikistan'], "key": 'TJ'},
        {"values": ['Tanzania, United Republic of'], "key": 'TZ'},
        {"values": ['Thailand'], "key": 'TH'},
        {"values": ['Timor-Leste'], "key": 'TL'},
        {"values": ['Togo'], "key": 'TG'},
        {"values": ['Tokelau'], "key": 'TK'},
        {"values": ['Tonga'], "key": 'TO'},
        {"values": ['Trinidad and Tobago'], "key": 'TT'},
        {"values": ['Tunisia'], "key": 'TN'},
        {"values": ['Tur"key"'], "key": 'TR'},
        {"values": ['Turkmenistan'], "key": 'TM'},
        {"values": ['Turks and Caicos Islands'], "key": 'TC'},
        {"values": ['Tuvalu'], "key": 'TV'},
        {"values": ['Uganda'], "key": 'UG'},
        {"values": ['Ukraine'], "key": 'UA'},
        {"values": ['United Arab Emirates'], "key": 'AE'},
        {"values": ['United Kingdom'], "key": 'GB'},
        {"values": ['United States'], "key": 'US'},
        {"values": ['United States Minor Outlying Islands'], "key": 'UM'},
        {"values": ['Uruguay'], "key": 'UY'},
        {"values": ['Uzbekistan'], "key": 'UZ'},
        {"values": ['Vanuatu'], "key": 'VU'},
        {"values": ['Venezuela'], "key": 'VE'},
        {"values": ['Viet Nam'], "key": 'VN'},
        {"values": ['Virgin Islands, British'], "key": 'VG'},
        {"values": ['Virgin Islands, U.S.'], "key": 'VI'},
        {"values": ['Wallis and Futuna'], "key": 'WF'},
        {"values": ['Western Sahara'], "key": 'EH'},
        {"values": ['Yemen'], "key": 'YE'},
        {"values": ['Zambia'], "key": 'ZM'},
        {"values": ['Zimbabwe'], "key": 'ZW'}
    ],
    "colors": [
        {
            "key": "black",
            "values": ["black"],
            "meta": {
                "rgba": [255, 255, 255, 1],
                "hex": "#000"
            }
        },
        {
            "key": "white",
            "values": ["white"],
            "meta": {
                "rgba": [0, 0, 0, 1],
                "hex": "#FFF"
            }
        },
        {
            "key": "red",
            "values": ["red"],
            "meta": {
                "rgba": [255, 0, 0, 1],
                "hex": "#FF0"
            }
        },
        {
            "key": "blue",
            "values": ["blue"],
            "meta": {
                "rgba": [0, 0, 255, 1],
                "hex": "#00F"
            }
        },
        {
            "key": "yellow",
            "values": ["yellow"],
            "meta": {
                "rgba": [255, 255, 0, 1],
                "hex": "#FF0"
            }
        },
        {
            "key": "green",
            "values": ["green"],
            "meta": {
                "rgba": [0, 255, 0, 1],
                "hex": "#0F0"
            }
        },
    ]
}


sentences = [('red and red are the main colors for Belize flag.', [(0, 2, 'colors'), (8, 10, 'colors'), (36, 41, 'country')]), ('My favourite color is black', [(22, 26, 'colors')]), ('My favourite color is red', [(22, 24, 'colors')]), ('green is the best color.', [(0, 4, 'colors')]), ('Virgin Islands, U.S. is the best country ever.', [(0, 19, 'country')]), ('Martinique flag containes yellow, white and black.', [(25, 30, 'colors'), (33, 37, 'colors'), (43, 47, 'colors'), (0, 9, 'country')]), ('My favourite color is red', [(22, 24, 'colors')]), ('blue is the main colors for Uganda flag.', [(0, 3, 'colors'), (28, 33, 'country')]), ('green is the main colors for Pitcairn flag.', [(0, 4, 'colors'), (29, 36, 'country')]), ('Dominican Republic is the best country ever.', [(0, 17, 'country')]), ('Croatia is the best country ever.', [(0, 6, 'country')]), ('Namibia and Nigeria are always in war.', [(0, 6, 'country'), (12, 18, 'country')]), ('green is the best color.', [(0, 4, 'colors')]), ('Venezuela flag containes green, blue and green.', [(25, 29, 'colors'), (32, 35, 'colors'), (41, 45, 'colors'), (0, 8, 'country')]), ('My favourite color is white', [(22, 26, 'colors')]), ('Timor-Leste and Estonia are always in war.', [(0, 10, 'country'), (16, 22, 'country')]), ('green is the main colors for Comoros flag.', [(0, 4, 'colors'), (29, 35, 'country')]), ('Syrian Arab Republic is the best country ever.', [(0, 19, 'country')]), ('red is the main colors for Kiribati flag.', [(0, 2, 'colors'), (27, 34, 'country')]), ("yellow is the main colors for Lao People'S Democratic Republic flag.", [(0, 5, 'colors'), (30, 61, 'country')]), ('Somalia is the best country ever.', [(0, 6, 'country')]), ('black is the best color.', [(0, 4, 'colors')]), ('white is the main colors for United States flag.', [(0, 4, 'colors'), (29, 41, 'country')]), ('Morocco and Niue are always in war.', [(0, 6, 'country'), (12, 15, 'country')]), ('My favourite color is white', [(22, 26, 'colors')]), ('Hong Kong and Tanzania, United Republic of are always in war.', [(0, 8, 'country'), (14, 41, 'country')]), ('Tanzania, United Republic of is the best country ever.', [(0, 27, 'country')]), ('Kenya flag containes white, black and green.', [(25, 29, 'colors'), (32, 36, 'colors'), (42, 46, 'colors'), (0, 4, 'country')]), ('My favourite color is blue', [(22, 25, 'colors')]), ('Mozambique flag containes green, blue and white.', [(25, 29, 'colors'), (32, 35, 'colors'), (41, 45, 'colors'), (0, 9, 'country')]), ('black is the main colors for Armenia flag.', [(0, 4, 'colors'), (29, 35, 'country')]), ('black and blue are the main colors for Cambodia flag.', [(0, 4, 'colors'), (10, 13, 'colors'), (39, 46, 'country')]), ('red is the main colors for Guernsey flag.', [(0, 2, 'colors'), (27, 34, 'country')]), ('My favourite color is yellow', [(22, 27, 'colors')]), ('My favourite color is green', [(22, 26, 'colors')]), ('Barbados is the best country ever.', [(0, 7, 'country')]), ('white is the best color.', [(0, 4, 'colors')]), ('red and black are the main colors for Falkland Islands (Malvinas) flag.', [(0, 2, 'colors'), (8, 12, 'colors'), (38, 64, 'country')]), ('My favourite color is green', [(22, 26, 'colors')]), ('green is the main colors for Slovenia flag.', [(0, 4, 'colors'), (29, 36, 'country')]), ('red and blue are the main colors for Djibouti flag.', [(0, 2, 'colors'), (8, 11, 'colors'), (37, 44, 'country')]), ('South Georgia and the South Sandwich Islands is the best country ever.', [(0, 43, 'country')]), ('Jamaica is the best country ever.', [(0, 6, 'country')]), ('My favourite color is red', [(22, 24, 'colors')]), ('Congo, The Democratic Republic of the is the best country ever.', [(0, 36, 'country')]), ('red is the main colors for Italy flag.', [(0, 2, 'colors'), (27, 31, 'country')]), ('South Georgia and the South Sandwich Islands flag containes yellow, yellow and black.', [(25, 30, 'colors'), (33, 38, 'colors'), (44, 48, 'colors'), (0, 43, 'country')]), ('black is the best color.', [(0, 4, 'colors')]), ('green is the best color.', [(0, 4, 'colors')]),
             ('My favourite color is blue', [(22, 25, 'colors')]), ('Chad and Niger are always in war.', [(0, 3, 'country'), (9, 13, 'country')]), ('Togo flag containes white, green and green.', [(25, 29, 'colors'), (32, 36, 'colors'), (42, 46, 'colors'), (0, 3, 'country')]), ('green is the best color.', [(0, 4, 'colors')]), ('Indonesia and French Southern Territories are always in war.', [(0, 8, 'country'), (14, 40, 'country')]), ('Qatar is the best country ever.', [(0, 4, 'country')]), ('Libyan Arab Jamahiriya is the best country ever.', [(0, 21, 'country')]), ('My favourite color is yellow', [(22, 27, 'colors')]), ('Marshall Islands flag containes red, yellow and white.', [(25, 27, 'colors'), (30, 35, 'colors'), (41, 45, 'colors'), (0, 15, 'country')]), ('green is the best color.', [(0, 4, 'colors')]), ('black and white are the main colors for Trinidad and Tobago flag.', [(0, 4, 'colors'), (10, 14, 'colors'), (40, 58, 'country')]), ('Kyrgyzstan flag containes green, red and red.', [(25, 29, 'colors'), (32, 34, 'colors'), (40, 42, 'colors'), (0, 9, 'country')]), ('green is the main colors for Tanzania, United Republic of flag.', [(0, 4, 'colors'), (29, 56, 'country')]), ('My favourite color is black', [(22, 26, 'colors')]), ('My favourite color is green', [(22, 26, 'colors')]), ('Malawi is the best country ever.', [(0, 5, 'country')]), ('Guatemala is the best country ever.', [(0, 8, 'country')]), ('black is the main colors for Spain flag.', [(0, 4, 'colors'), (29, 33, 'country')]), ('yellow is the best color.', [(0, 5, 'colors')]), ('green and yellow are the main colors for French Guiana flag.', [(0, 4, 'colors'), (10, 15, 'colors'), (41, 53, 'country')]), ('black and green are the main colors for Israel flag.', [(0, 4, 'colors'), (10, 14, 'colors'), (40, 45, 'country')]), ('white is the best color.', [(0, 4, 'colors')]), ('My favourite color is green', [(22, 26, 'colors')]), ('Japan is the best country ever.', [(0, 4, 'country')]), ('red and yellow are the main colors for Bosnia and Herzegovina flag.', [(0, 2, 'colors'), (8, 13, 'colors'), (39, 60, 'country')]), ('yellow is the main colors for Jersey flag.', [(0, 5, 'colors'), (30, 35, 'country')]), ('yellow is the best color.', [(0, 5, 'colors')]), ('Afghanistan is the best country ever.', [(0, 10, 'country')]), ('Nauru is the best country ever.', [(0, 4, 'country')]), ('My favourite color is white', [(22, 26, 'colors')]), ('My favourite color is black', [(22, 26, 'colors')]), ('Mexico flag containes black, blue and green.', [(25, 29, 'colors'), (32, 35, 'colors'), (41, 45, 'colors'), (0, 5, 'country')]), ('Virgin Islands, British and Botswana are always in war.', [(0, 22, 'country'), (28, 35, 'country')]), ('My favourite color is red', [(22, 24, 'colors')]), ('white is the best color.', [(0, 4, 'colors')]), ('Madagascar and Eritrea are always in war.', [(0, 9, 'country'), (15, 21, 'country')]), ('white is the best color.', [(0, 4, 'colors')]), ('Somalia and New Zealand are always in war.', [(0, 6, 'country'), (12, 22, 'country')]), ('green is the main colors for Comoros flag.', [(0, 4, 'colors'), (29, 35, 'country')]), ('Suriname is the best country ever.', [(0, 7, 'country')]), ('blue is the best color.', [(0, 3, 'colors')]), ('Guinea and Libyan Arab Jamahiriya are always in war.', [(0, 5, 'country'), (11, 32, 'country')]), ('blue is the best color.', [(0, 3, 'colors')]), ('black is the main colors for Bhutan flag.', [(0, 4, 'colors'), (29, 34, 'country')]), ('black is the best color.', [(0, 4, 'colors')]), ("white and yellow are the main colors for Cote D'Ivoire flag.", [(0, 4, 'colors'), (10, 15, 'colors'), (41, 53, 'country')]), ('My favourite color is white', [(22, 26, 'colors')]), ('My favourite color is red', [(22, 24, 'colors')]), ('Turks and Caicos Islands is the best country ever.', [(0, 23, 'country')]), ('white and white are the main colors for Iraq flag.', [(0, 4, 'colors'), (10, 14, 'colors'), (40, 43, 'country')]), ('Faroe Islands flag containes black, green and green.', [(25, 29, 'colors'), (32, 36, 'colors'), (42, 46, 'colors'), (0, 12, 'country')])]

ner = lner('en', sentences, entities, )

ner.process()

print(ner.data)

ner.train(epochs=20, batch_size=8, model_name="countries_colors_v1")

# entities = ner.recognize("Blue is not in egypt flag.")

# print(entities)
